// <auto-generated />
namespace EURIS.VideoStream.Entity.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class intial_model : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(intial_model));
        
        string IMigrationMetadata.Id
        {
            get { return "202003242118082_intial_model"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
